language: node_js
node_js:
- '12.13'
before_script: yarn install
script: yarn build
cache:
  directories:
  - "./node_modules"
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
