language: node_js
node_js:
- '12'
before_script: yarn install
script: yarn build
cache:
  yarn: true
  directories:
  - "./node_modules"
deploy:
  provider: npm
  email: jaccobkii@gmail.com
  api_key:
    secure: L6PYjJiYQL83d4XQi5T9WxwFuEA+wKyDxbwKo+1SQGsaB0Cdx9V49If+MARA5ZpWY58iPctWpasewwX6DlU/ihdSSVQurFmRP/xebDLA7X0VJJ0rEL0GOVlN0wyPDMJo9/+Tlc7eBNutLq9exSEYBUK5ReQ0J8g4wxNSxUKyRQSuepaGC+INN5uS7XB8oXnsgfdnbq2a9uBI28WC7uv81kbftc9cZPttGTa47F3hnY1qTofvOSCWOK+NFO/p62Tz371RLCapdrxeIw4nDQ2iAYiGStXKftS3hlDC57bYaLaifqxEiamCGKqlEzFglsAhMBTGgVQ2ngndxfUYWpZBCE3+lPc6zUaDlTuDktdlGANIaDC179WRY7wVWp8MI0aeQ2Yn8GtIFz6Mywjw0hpcVrjZ4YMe8bdD3WTNaWvP05gLN7cy/cbcRPLhx1qEYtF/KI+nMoVEvuUv6wHtcQRLDt1fYlfTYCv2C5cptM4snjc6zeJcjP8I6ASjZcK2Z71xbqo6c9Z7YJrlozIiMyEFo+XqtcyOc+Oe79q0M9hVn/SpywG+CniKn65B40T0xBGg80UaGaIqWm9vPwinoaRb/lyqxYW7ohCfr8hEUTHzkX69+G4ft7K469L9siPy/95wc/X8RCb7smcMPmQXPpc7SslhW20eWyY6LVkkaZMi5ms=
  on:
    repo: zeno-hentai/zht-client-api
