language: node_js
node_js:
- '12.13'
before_script: yarn install
script: yarn build
cache:
  directories:
  - "./node_modules"
deploy:
  provider: npm
  email: jaccobkii@gmail.com
  api_key:
    secure: dfPuvJZFw8NriR8SrU5zgiKPx78REN5deIDUsV6Cs9Gq7KLRcnHbcb2Be7xFXvjcvE3vn6Qtj376b2kfAKGNTtSc3ArHY5gCY0CBnlQNnIxDjZ2/zWIf0Hb2PaBm7gO/26FkIbsdG+nBPqwloEkWYVrfKzVQ7PotEAfcx63N8Nuo7qxyuCFb0ZRiam+N0bIlzFxXOPDLdEQJPEtm++lgWCBYLhP3VPjhjGafZi9BhAT6hbfUzuy8Air2MUSN6Dwe8DOGrvtXjN0+4AOjFyvBRQun4p76kUzXvtQak/VYUykZXbNMPdVnFIpkWIj+XUECFqVDxtF03vtywLzlWtxHFT4f1OBnKsFtZ/S8Q5G1pQ5gNUDoRW8L1NGyOw+xqmwRVK28r87L0IdS63Yg2zfoWYN3iiaKwtd8ozeKVbKhgXu8L2MZcKgrQsi9ynMNCt2+lwv5qrqWVPi8dXOlYbzf42AgKA7qKKGrStK9RajKFFuidElnbJgk5RqGO0+4D2i6jKnJkmkIK2E+mWjUdEX3sCywq8czUEN5y3f+G6ppBdiMECJifnaC68yrNUu7ZjQhVu/PkFI05b9unAIK7Y+57s5CKtRxg7gQBZZj5on6zbkmPVVRATk8C48pjWZkoz9bKqw3eWvgm+wr0ryq5z0/VTkPMmjjfEXV0QpD5JjdEYc=
